export const ESSENTIAL_MIN_LENGTH = 1

// 사용자
export const EMAIL_MAX_LENGTH = 50
export const EMAIL_MIN_LENGTH = 1
export const PASSWORD_MIN_LENGTH = 8
export const PASSWORD_MAX_LENGTH = 100
export const NICKNAME_MAX_LENGTH = 50
export const NICKNAME_MIN_LENGTH = 1
export const SELLER_DESCRIPTION_MAX_LENGTH = 200
export const SELLER_DESCRIPTION_MIN_LENGTH = 0
export const LINK_URLS_MAX_BYTE = 65535

// 계좌
export const ACCOUNT_HOLDER_MAX_LENGTH = 50
export const ACCOUNT_HOLDER_MIN_LENGTH = 1
export const BANK_NAME_MAX_LENGTH = 50
export const BANK_NAME_MIN_LENGTH = 1
export const BANK_ACCOUNT_MAX_LENGTH = 50
export const BANK_ACCOUNT_MIN_LENGTH = 1

// 배송지
export const ADDRESS_DETAIL_MAX_LENGTH = 100
export const ADDRESS_DETAIL_MIN_LENGTH = 1

// 검색
export const SEARCH_MAX_LENGTH = 20

// 쿠폰
export const COUPON_NAME_MAX_LENGTH = 25
export const COUPON_CONTENT_MIN_LENGTH = 10
export const COUPON_CONTENT_MAX_LENGTH = 50
export const COUPON_PRICE_MAX_NUMBER = 50000
export const COUPON_PRICE_MIN_NUMBER = 1000
export const COUPON_STOCK_MAX_NUMBER = 1000000
export const COUPON_STOCK_MIN_NUMBER = 1
export const COUPON_EVENT_START_TO_END_MIN_HOUR = 1
export const COUPON_EVENT_END_TO_EXPIRE_MIN_HOUR = 24

// 이미지
export const IMAGE_MAX_MB = 10

// 프로젝트
export const PROJECT_TITLE_MAX_LENGTH = 50
export const PROJECT_TITLE_MIN_LENGTH = 1
export const PROJECT_DESCRIPTION_MAX_LENGTH = 100
export const PROJECT_DESCRIPTION_MIN_LENGTH = 10
export const PROJECT_START_ENABLE_AFTER_NOW = 7
// export const PROJECT_END_ENABLE_AFTER_FROM_START = 30 
export const PROJECT_MARKDOWN_MAX_BYTE = 65535
export const PROJECT_MARKDOWN_MIN_BYTE = 0
export const PROJECT_IMAGE_GROUP_MAX_COUNT = 5
// export const PROJECT_IMAGE_GROUP_MIN_COUNT = 1
export const PROJECT_TARGET_AMOUNT_MAX_NUMBER = 1000000000
export const PROJECT_TARGET_AMOUNT_MIN_NUMBER = 1000000

// 상품
export const PRODUCT_NAME_MAX_LENGTH = 25
export const PRODUCT_NAME_MIN_LENGTH = 1
export const PRODUCT_DESCRIPTION_MAX_LENGTH = 50
export const PRODUCT_DESCRIPTION_MIN_LENGTH = 0
export const PRODUCT_AMOUNT_MAX_NUMBER = 1000000000
export const PRODUCT_AMOUNT_MIN_NUMBER = 100
export const PRODUCT_STOCK_MAX_NUMBER = 10000
export const PRODUCT_STOCK_MIN_NUMBER = 1

// 후기
export const REVIEW_CONTENT_MAX_LENGTH = 1000
export const REVIEW_CONTENT_MIN_LENGTH = 1