import type { Metadata } from "next";
import localFont from "next/font/local"; // 지정한 폰트를 사용하기 위해 불러옴
import "./globals.css";
import HeaderLoader from "@/components/HeaderLoader";
import RegisterPageButtonLoader from "@/components/RegisterPageButtonLoader";
import  AuthProvider from "@/components/AuthProvider";
import { AuthGate } from "@/components/login/AuthGate";

// 로그인 토큰 관련
import { AuthProvider } from '../contexts/AuthContext';

// Pretendard 폰트를 사용하기 위해 불러옴
const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${pretendard.variable} font-pretendard`} // Pretendard 사용
      >
        <AuthProvider>
          <AuthGate />
          <HeaderLoader />
          <main className="flex-1 bg-white mt-1">
            <div className="container mx-auto px-4 py-8">
            {children}
          </div>
            <RegisterPageButtonLoader />
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
