import type { Metadata } from "next";
import localFont from "next/font/local"; // 지정한 폰트를 사용하기 위해 불러옴
import "./globals.css";
import Header from "@/components/header/Header";

// Pretendard 폰트를 사용하기 위해 불러옴
const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className}`} // Pretendard 사용
      >
        <Header />
        <main className="min-h-screen bg-white">
          <div className="container mx-auto px-4 py-8">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
